### PR TITLE
Buy via USD price

### PR DESCRIPTION
**Pull request by caseypugh**
Specify how much you want to buy via USD rather than amount of coins.
```
TEST=1 bundle exec ruby trader.rb buy 25USD ETH
```

### CODE REVIEW

**Comment by jamiew** [comment]
Nice

What do you think of using "$25" instead of "25USD"?

**Comment by caseypugh** [comment]
First thing i tried but couldn't get it to parse correctly

**Comment by jamiew** [comment]
Cool I'll hack around

**Comment by jamiew** [comment]
So you have to do "\\$5" (with a backslash) so will just stick with 5USD 👍

**Pull request merged**
